namespace Umea.se.EstateService.ServiceAccess.Pythagoras.Enums;

public enum PropertyCategoryId
{
    BlueprintAvailable = 13,
    PropertyDesignation = 56,
    FacilityServiceOrder = 79,
    MunicipalityArea = 209,
    OperationalArea = 208,
    EstateExternalStatus = 210,
    EstateExternalOwnerName = 213,
    EstateExternalOwnerNote = 214,
    YearOfConstruction = 226,
    BuildingCondition = 228,
    BuildingExternalStatus = 233,
    BuildingExternalOwnerName = 234,
    BuildingExternalOwnerNote = 236,
    NoticeBoardText = 239,
    NoticeBoardStartDate = 240,
    NoticeBoardEndDate = 241,
    AdministrativeArea = 250,
    PropertyManager = 282,
    OperationsManager = 283,
    OperationCoordinator = 284,
    RentalAdministrator = 285,
    TownHallServiceOrder = 289,
    OperationsTechnician = 304,
    Caretaker = 305,
    PropertyManagerContact = 306,
    OperationsManagerContact = 307,
    OperationCoordinatorContact = 308,
    RentalAdministratorContact = 309,
    CaretakerContact = 310,
    OperationsTechnicianContact = 311,
}
