name: $(buildName)_$(Date:yyyy-MM-ddTHH.mm.ss)

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: Turkos/ume-pipeline-templates
      ref: refs/tags/release/v260213T1327-15561

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - test
      - prod

  - name: shouldAutoDeployJobPicker
    displayName: Auto-deploy modified systems
    type: boolean
    default: true

  - name: updateEstateServiceDatabaseJobPicker
    displayName: Update ume-sqldb-estateservice
    type: boolean
    default: false

  - name: buildAndDeployEstateServiceJobPicker
    displayName: Deploy ume-app-estateservice
    type: boolean
    default: false

  - name: buildAndDeployEstatePlatformJobPicker
    displayName: Deploy ume-stapp-estateplatform
    type: boolean
    default: false

variables:
  - template: pipelines/general/template-default-pipeline-variables.yml@templates
    parameters:
      environment: ${{ parameters.environment }}

  - group: ume-rg-estateplatform-${{ parameters.environment }}

stages:
  - stage: ValidateRequestStage
    displayName: Validate Request
    jobs:
      - template: pipelines/general/template-fail-on-condition.yml@templates
        parameters:
          failCondition: >-
            and(
              eq('${{ parameters.environment }}', 'prod'),
              not(startsWith(variables['Build.SourceBranch'], 'refs/tags/release/'))
            )
          errorMessage: Manual deployments to prod are only allowed from release tags.

  - stage: CheckForChangesStage
    displayName: Check for changes
    dependsOn: ValidateRequestStage
    condition: >-
      and(
        not(or(failed(), canceled())),
        eq('${{ parameters.shouldAutoDeployJobPicker }}', 'true')
      )
    jobs:
      - template: pipelines/general/template-check-for-changes.yml@templates
        parameters:
          paths:
            - src/ume-app-estateservice/Umea.se.EstateService.DataStore/Migrations
            - src/ume-app-estateservice
            - src/ume-stapp-estateplatform

  # ume-sqldb-estateservice
  - stage: UpdateEstateServiceDatabaseStage
    displayName: Update EstateService Database
    dependsOn: CheckForChangesStage
    variables:
      changedPaths: $[ dependencies.CheckForChangesStage.outputs['Job.Task.CHANGED_PATHS'] ]
    condition: >-
      and(
        not(or(failed(), canceled())),
        or(
          eq(${{ parameters.updateEstateServiceDatabaseJobPicker }}, true),
          and(
            eq('${{ parameters.shouldAutoDeployJobPicker }}', 'true'),
            contains(variables['changedPaths'], 'Umea.se.EstateService.DataStore/Migrations')
          )
        )
      )
    jobs:
      - template: pipelines/azure/template-update-database.yml@templates
        parameters:
          environment: ${{ parameters.environment }}
          azureSubscription: $(serviceConnection)
          projectFolderName: ume-app-estateservice
          startupProjectName: Umea.se.EstateService.API
          databaseProjectName: Umea.se.EstateService.DataStore
  # ------

  # EstateService
  - stage: BuildEstateServiceStage
    displayName: Build EstateService
    dependsOn:
      - CheckForChangesStage
      - UpdateEstateServiceDatabaseStage
    variables:
      changedPaths: $[ dependencies.CheckForChangesStage.outputs['Job.Task.CHANGED_PATHS'] ]
    condition: |
      and(
        not(or(failed(), canceled())),
        or(
          eq(${{ parameters.buildAndDeployEstateServiceJobPicker }}, true),
          and(
            eq('${{ parameters.shouldAutoDeployJobPicker }}', 'true'),
            contains(variables['changedPaths'], 'ume-app-estateservice')
          )
        )
      )
    jobs:
      - template: pipelines/azure/template-build-backend.yml@templates
        parameters:
          projectFolderName: ume-app-estateservice
          entrypointProjectName: Umea.se.EstateService.API

  - stage: DeployEstateServiceStage
    displayName: Deploy EstateService
    dependsOn: BuildEstateServiceStage
    condition: >-
      and(
        succeeded('BuildEstateServiceStage'),
        or(
          eq(dependencies.UpdateEstateServiceDatabaseStage.result, 'Succeeded'),
          eq(dependencies.UpdateEstateServiceDatabaseStage.result, 'Skipped')
        )
      )
    jobs:
      - template: pipelines/azure/template-deploy-backend.yml@templates
        parameters:
          azureSubscription: $(serviceConnection)
          environment: ${{ parameters.environment }}
          resourceGroup: ume-rg-estateplatform-${{ parameters.environment }}
          appName: ume-app-estateservice-${{ parameters.environment }}
          projectFolderName: ume-app-estateservice
          pingEndpoints:
            - /index.html
            - /api/v1.0/home/ping
  # ------

  # EstatePlatform
  - stage: BuildEstatePlatformStage
    displayName: Build EstatePlatform
    dependsOn: CheckForChangesStage
    variables:
      changedPaths: $[ dependencies.CheckForChangesStage.outputs['Job.Task.CHANGED_PATHS'] ]
    condition: >-
      and(
        not(or(failed(), canceled())),
        or(
          eq(${{ parameters.buildAndDeployEstatePlatformJobPicker }}, true),
          and(
            eq('${{ parameters.shouldAutoDeployJobPicker }}', 'true'),
            contains(variables['changedPaths'], 'ume-stapp-estateplatform')
          )
        )
      )
    jobs:
      - template: pipelines/azure/template-build-frontend.yml@templates
        parameters:
          environment: ${{ parameters.environment }}
          projectFolderName: ume-stapp-estateplatform

  - stage: DeployEstatePlatformStage
    displayName: Deploy EstatePlatform
    dependsOn: BuildEstatePlatformStage
    condition: >-
      and(
        not(or(failed(), canceled())),
        succeeded('BuildEstatePlatformStage')
      )
    jobs:
      - template: pipelines/azure/template-deploy-frontend.yml@templates
        parameters:
          environment: ${{ parameters.environment }}
          projectFolderName: ume-stapp-estateplatform
          deploymentToken: $(estateplatform-deployment-token)
  # ------
