using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Umea.se.EstateService.API.Extensions;
using Umea.se.EstateService.API.Requests;
using Umea.se.EstateService.Logic.Handlers;
using Umea.se.EstateService.Logic.Handlers.Blueprint;
using Umea.se.EstateService.Logic.Models;
using Umea.se.EstateService.Shared.Models;

namespace Umea.se.EstateService.API.Controllers;

[ApiController]
[Produces("application/json")]
[Route(ApiRoutes.Floors)]
[Authorize]
public class FloorController(IFloorBlueprintService blueprintService, IEstateDataQueryHandler pythagorasHandler) : ControllerBase
{

    /// <summary>
    /// Retrieves metadata for a specific floor.
    /// </summary>
    /// <param name="floorId">The floor identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The requested floor metadata.</returns>
    [HttpGet("{floorId:int}")]
    [SwaggerOperation(
        Summary = "Get floor",
        Description = "Retrieves metadata for a floor using the floorIds[] filter."
    )]
    [SwaggerResponse(StatusCodes.Status200OK, "Floor metadata", typeof(FloorInfoModel))]
    [SwaggerResponse(StatusCodes.Status404NotFound, "Floor not found.")]
    public async Task<ActionResult<FloorInfoModel>> GetFloorAsync(
        int floorId,
        CancellationToken cancellationToken)
    {
        IReadOnlyList<FloorInfoModel> floors = await pythagorasHandler
            .GetFloorsAsync([floorId], queryArgs: null, cancellationToken)
            .ConfigureAwait(false);

        if (floors.Count == 0)
        {
            return NotFound();
        }

        return Ok(floors[0]);
    }

    /// <summary>
    /// Retrieves a floor blueprint in PDF or SVG format.
    /// </summary>
    /// <remarks>
    /// Streams the floor blueprint generated by Pythagoras.
    /// </remarks>
    /// <param name="floorId">The floor identifier.</param>
    /// <param name="request">Blueprint request parameters.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    [HttpGet("{floorId:int}/blueprint")]
    [SwaggerOperation(
        Summary = "Get floor blueprint",
        Description = "Streams a floor blueprint as PDF or SVG."
    )]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status502BadGateway)]
    public async Task<IActionResult> GetFloorBlueprintAsync(
        int floorId,
        [FromQuery] FloorBlueprintRequest request,
        CancellationToken cancellationToken)
    {
        FloorBlueprint blueprint = await blueprintService
            .GetBlueprintAsync(floorId, request.Format, request.IncludeWorkspaceTexts, cancellationToken)
            .ConfigureAwait(false);

        blueprint.Content.Position = 0;

        Response.SetPublicCacheHeaders(blueprint.ContentEncoding);

        return File(blueprint.Content, blueprint.ContentType, blueprint.FileName);
    }
}
